[package]
name = "volfied-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies.sdl2]
version = "0.36"
default-features = false
features = ["ttf","image","mixer"]